---
title: "R Notebook"
output: html_notebook
---

# Links

Access raw database: https://chrisk91.me/2018/02/03/Accessing-the-Anki-database-via-R.html

# Libraries

```{r}
library(tidyverse)
library(RSQLite)
library(DBI)
library(jsonlite)
theme_set(theme_classic())
```

# Access the database

```{r}
source("../data/config.R")
connection <- dbConnect(SQLite(), dbname=appdata_path)

result <- dbSendQuery(connection, "SELECT * from cards")
cardData <- dbFetch(result)
dbClearResult(result)

result <- dbSendQuery(connection, "SELECT * from col")
collectionData <- dbFetch(result)
dbClearResult(result)

result <- dbSendQuery(connection, "SELECT * from notes")
notesData <- dbFetch(result)
dbClearResult(result)

result <- dbSendQuery(connection, "SELECT * from revlog")
revisionData <- dbFetch(result)
dbClearResult(result)

dbDisconnect(connection)
```


# First parsing

Deck ID loaded from config file (1550758092309)

```{r}
# 1579686732242


character_ids <- cardData %>% 
    filter(did == chinese_character_deck_id) %>% 
    dplyr::select(card_id=id, notes_id=nid)

notes_df <- notesData %>% mutate(notes_id=id)

character_ids_w_char <- character_ids %>% 
    dplyr::inner_join(notes_df, by="notes_id") %>% 
    dplyr::select(card_id, notes_id, character=sfld, back=flds)
head(character_ids_w_char)

revlog_df <- revisionData %>% 
    dplyr::rename(card_id=cid) %>% 
    filter(card_id %in% character_ids_w_char$card_id) %>%
    inner_join(character_ids_w_char %>% dplyr::select(card_id, character, back), by="card_id") %>%
    mutate(duration=ifelse(lastIvl < 0, -lastIvl/3600/24, lastIvl))

revlog_df_w_nbr <- revlog_df %>% 
    group_by(card_id) %>% 
    group_map(~.x %>% mutate(nbr=seq_len(n())), keep = TRUE) %>% 
    do.call("rbind", .)

top_difficult_cards <- revlog_df_w_nbr %>% 
    group_by(card_id) %>% 
    summarize(
        reviews=length(id), 
        curr_dur=tail(lastIvl, 1), 
        curr_ease=sprintf("ease_%s", tail(ease, 1)),
        avg_ease=mean(ease)
    ) %>% 
    mutate(curr_dur=ifelse(curr_dur<0, 0, curr_dur)) %>%
    arrange(desc(reviews))

top_difficult_df <- top_difficult_cards %>% inner_join(character_ids_w_char, by="card_id")
write_tsv(top_difficult_df, path = "../parsed_data/top_difficult.tsv")
write_tsv(revlog_df_w_nbr, path = "../parsed_data/all_reviews.tsv")

revlog_df
character_ids_w_char

# notes_df <- read_tsv("../data/notes.tsv") %>% mutate(id=as.character(id))
# table(notes_df$id %in% character_ids)
```

# Getting recently failed

```{r}
one_week_ago <- Sys.time() - (7 * 24 * 3600)
one_week_ago_in_millisec <- as.numeric(one_week_ago) * 1000

one_week_ago_in_millisec

table(revlog_df$id > one_week_ago_in_millisec)

recently_failed_reviews <- revlog_df %>% 
    filter(type==1 & 
               ease==1 & 
               id > one_week_ago_in_millisec)

recently_failed_reviews %>% pull(character) %>% table()
recently_failed_reviews


```

# Final step: Parse input to ChineseInSpace format

`charToRaw` from `base` package seems to be the key!

ā á ǎ à ē é ě è ī í ǐ ì ō ó ǒ ò ū ú ǔ ù ǖ ǘ ǚ ǜ 

pinyin::py Able to retrieve pinyin for character

https://github.com/pzhaonet/pinyin

Using pinyin pydict to parse!

```{r}
library(pinyin)

get_tones <- function(characters, pydict) {
    pinyin::py(characters, dic = pydict) %>% 
        map(~rev(strsplit(., "")[[1]])[1])
}

mypy_toneless = pydic(method = 'toneless')
mypy_normal = pydic(method = 'quanpin')
mypy_tone = pydic(method = 'tone')

head(character_ids_w_char)$back %>% map(~strsplit(., " ")[[1]][2])

parsed_for_output <- recently_failed_reviews %>% mutate(character=character %>% gsub(" .*", "", .)) %>% distinct(character, .keep_all = TRUE)
target_chars <- parsed_for_output %>% pull(character)

parsed_for_output

parsed_for_output

meanings <- parsed_for_output$back %>% 
    gsub("<br>.*", "", .) %>% 
    gsub(".*\\. ", "", .) %>% 
    str_extract(" .*") %>% 
    gsub("^ ", "", .) 



failed_chars_df <- data.frame(
    raw_char=target_chars,
    descr=parsed_for_output$back,
    char=target_chars,
    meaning=meanings,
    pinyin=pinyin::py(target_chars, dic=mypy_normal) %>% unlist(),
    base_pinyin=pinyin::py(target_chars, dic=mypy_toneless) %>% unlist(),
    tone=get_tones(target_chars, mypy_tone) %>% unlist()
)

parsed_for_output$back %>% map(~gsub(".*\\.", "", .) %>% gsub("<br>", " ", .) %>% gsub("^ +", "", .))

failed_chars_df

output_path <- sprintf("%s/%s", output_dir, "recently_failed.txt")
message("Writing to", output_path)
write_tsv(failed_chars_df, path=output_path)
```










